### ISSUE TITLE
lrmiData Endpoint GET Request

### ISSUE THREAD

**Issue by inkuss** [hbz/to.science.api#347]
der lrmiData Endpoint benötigt auch einen GET-Request; bisher geht nur POST.
Der GET soll die LRMI-Metadaten genauso zurück liefern, wie sie ge-postet wurden, jedoch angereichert um die ID.
z.B.
id: https://api.hoerkaen.hbz-nrw.de/resource/oer:16

**Comment by aquast** [comment]
Meine Überlegung war ursprünglich, dass der LRMI ebenso wie z.B. lobid, rdf, openaire oder wgl_dc mittels "Content-Negotiation" wieder zurückgegeben werden können.

Beispiele, was ich damit meine:

https://frl.publisso.de/resource/frl:6426037.json2
https://frl.publisso.de/resource/frl:6426037.rdf
https://frl.publisso.de/resource/frl:6426037.openaire

Diese Umsetzung war vergleichsweise einfach und würde aus meiner Sicht völlig ausreichend sein :-)

**Comment by inkuss** [comment]
Ich habe den GET Request schon umgesetzt (ist z.Zt. nur auf localhost), das war kein großer Aufwand.
Werde mir aber mal angucken, was mit "Content-Navigation" gemeint ist.

**Comment by aquast** [comment]
ok, super :-)

**Comment by aquast** [comment]
Content-Negotiation - Habe ich in Ausrufezeichen gesetzt., weil dass was ich beschrieben habe nach meinem Verständnis **keine echte** Content-Negotiation ist.

Eigentlich versteht man darunter, dass der Http-Client im Accept-Header des Requests angibt welches Format er haben möchte und je nach Anfrage dann ein unterschiedliches Format bekommt. 

https://de.wikipedia.org/wiki/Content_Negotiation

Wir haben aber eine Schnittstelle, die je nach Dateiendung unterschiedliche Formate ausgibt.

**Comment by inkuss** [comment]
Bei Metadata2 kann man im Accept Header folgende Formate angeben: application/rdf+xml, text/turtle, text/plain. Das intern-Format wird dann entsprechend gewandelt. Dazu gibt es eine Methode in RdfUtils.
Für LRMI-Data habe ich das nicht übernommen. Sonst müssten die Daten intern im RDF-Format vorliegen.
Bei LRMI-Data wird einfach immer JSON zurück gegeben.

Die Schnittstelle, die je nach Dateiendung unterschiedliche Formate ausgibt, ist glaube ich etwas anderes als der GET-Request.

**Comment by inkuss** [comment]
Habe ich es richtig verstanden, dass in der "id" immer die wirkliche Ressource-ID im System stehen soll,
also z.B. https://api.hoerkaen.hbz-nrw.de/resource/oer:16 ?
Ich vermute, dass soll auch schon bei Anlage des Lrmidata-Datenstroms (POST) dort hinein geschrieben werden und dort bereits drin stehende Werte überschreiben ? Das müsste ich noch realisieren.

Das klingt nicht ganz einfach, weil dazu das JSON geparst und verändert werden müsste.

**Comment by inkuss** [comment]
Den GET-Request habe ich ebenfalls auf hoerkaen ausgerollt, funktioniert so z.B.
curl -i -$USR:$PASSWD --key metromorph.key --cert metromorph.crt -XGET https://api.hoerkaen.hbz-nrw.de/resource/oer:17/lrmiData -H "Content-Type:application/json;charset=utf-8";echo

Ersetzen von IDs - wie in Telko besprochen (z.B. toscience-ID in mainEntityOfPage) müsste noch gemacht werden. Eigentlich ist das ein anderes Ticket.

**Comment by inkuss** [comment]
GET Request OK
