### ISSUE TITLE
Annoying Casting Issue with unknown reason

### ISSUE THREAD

**Issue by aquast** [hbz/to.science.api#383]
For an unknown reason mapping of lrmiData results in two different data structures. We either get:

```
"creator": [
    {
      "@id": "https://orcid.org/0000-XXXX-XXXX-XXXX",
      "academicDegree": "Prof.",
      "affiliation": {
        "@id": "https://ror.org/024z2rq82",
        "prefLabel": "Heinrich-Heine-Universität Düsseldorf",
        "type": "Organization"
      },
      "prefLabel": "Tycho Typo"
    },
```
Affiliation in this case is of type Json Object
Or we get:

```
  "creator": [
    {
      "@id": "https://api.hoerkaen.hbz-nrw.de/adhoc/uri/RmlvbmEgRmllc2Vsc2Nod2VpZg==",
      "academicDegree": "https://d-nb.info/standards/elementset/gnd#academicDegree/Prof.",
      "affiliation": [
        {
          "@id": "https://ror.org/027b9qx26",
          "prefLabel": "Hochschule Niederrhein",
          "rdftype": [
            {
              "@id": "http://schema.org/Organization",
              "prefLabel": "http://schema.org/Organization"
            }
          ]
        }
      ],
      "prefLabel": "Fiona Fieselschweif"
    },

```
Where Affiliation is of type Json Array.  I can find a reason for this behavior. 

- [ ] From https://dini-ag-kim.github.io/amb/draft/schemas/creator.json the affiliation should be a Json Object. Is that correct @TobiasNx ?
- [ ] My assumption is that the reason for the difference in the Object Type mapping may lies within etikett data. Is that correct @jschnasse  ?

 

, nor can say which is the correct type we have to implement.

**Comment by inkuss** [comment]
Das mit rdftype vs. type is ein Ansatzpunkt. Ich kann mich erinnern, dass ich anfänglich mal "Organization" hart reingeschrieben habe, also ohne @id. Ich gucke ab 15 Uhr mal in die Sourcen.
Die anderen Unterschiede scheinen mir daher zu kommen, dass der eine Autor eine ORCID-ID hat, der andere nicht, sondern nur eine AdHoc id.

**Comment by TobiasNx** [comment]
It should be an object, see:

https://dini-ag-kim.github.io/amb/draft/schemas/affiliation.json

**Comment by TobiasNx** [comment]
btw. it shouldnt be academicDegree but honorificPrefix (or honoricPrefix which is the faulty info from the upload formular)

**Comment by inkuss** [comment]
Evtl. hängen die Unterschiede auch damit zusammen, ob das Mapping erstmalig stattfindet (Senden übe das List-Formular inkl. Mapping) oder durch erneutes Editieren zustande kommt (ORCA-Formular).

**Comment by inkuss** [comment]
honoricPrefix heißt es in LRMI, academicDegree in RDF. Das Beispiel ist RDF (...aber darüber bin ich auch erst gestolpert).

**Comment by inkuss** [comment]
deswegen heißt es auch prefLabel (RDF) und nicht name (LRMI).

**Comment by aquast** [comment]
> btw. it shouldnt be academicDegree but honorificPrefix (or honoricPrefix which is the faulty info from the upload formular)

@TobiasNx My examples are from lobid data not from lrmiData. Therefore academicDegree is correct ;-)
Oh, @inkuss already mentioned this

**Comment by aquast** [comment]
btw. I now prevent code from runtime errors by cast HashSet into ArrayList if requiered. BUT this means I also loose all information of sequence that is normally part of ArrayList. Therefore I'm on the way to provide a manual  circumvent for this situation

**Comment by aquast** [comment]
Inspecting the code and check for the issue I learned it's not a bug. It's a missconception in the way we use JSONObjects. Therefore I close this issue.
